name: Feature Request
description: Suggest an idea for this project
title: '[Feature request]: '
type: 'Feature'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature request!
  - type: textarea
    id: feature-description
    attributes:
      label: Feature request and related problem
      description: A clear and concise description of what the problem is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternatives
      description: Clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
